### PR TITLE
Feat: configure custom Docker Registry mirror if needed

### PR DESCRIPTION
**Pull request by kelvintaywl**
This PR is to enable additional configurations for setting up [a custom Docker registry mirror](https://docs.docker.com/registry/recipes/mirror/).

This is based on an earlier **tested** work on behalf of a Server 3.x customer.

Original work's [diff here](https://github.com/CircleCI-Public/circleci-server-windows-image-builder/compare/master...kelvintaywl:circleci-server-windows-image-builder:custom-docker-registry-mirror?expand=1)

### next steps

- [ ] Port these changes to our https://github.com/CircleCI-Public/circleci-server-linux-image-builder

### CODE REVIEW

**Comment by kelvintaywl** [comment]
a lot of the work here was actually contributed by @nanophate (thank you so much!)

**Review by makotom — COMMENTED** [review]
Though a minor comment. Otherwise LGTM!

**Comment by makotom** [comment]
@ryanwohara I think we need you to :stamp: and :merge: 🙏

**Comment by ryanwohara** [comment]
I cannot merge this because of the required status. I need to file an IT ticket I think.

**Comment by ryanwohara** [comment]
Good2go

**Pull request merged**
